projects:
  web3chat:
    schemaPath: amplify/backend/api/web3chat/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 6
extensions:
  amplify:
    version: 3
